---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
    - "recipe[apt::default]"
    - "recipe[rundeck::node_unix]"

suites:
  - name: server
    run_list:
      - "recipe[rundeck::server]"
      - "recipe[create_chef_dir]"
      - "recipe[rundeck::chef-rundeck]"
    attributes:
      rundeck:
        hostname: 'localhost'
        security_roles: ['superusers', 'run_only_users']
        plugins:
          webdav-logstore:
            url: 'https://raw.github.cerner.com/rundeck/rundeck/2.1_plugin_lwrp/test/integration/server/webdav-logstore-2.1.0.jar'
            checksum: '5bc93e6dc52a86a9190110fc7f3ebc4d80ee0021ee6b39642b501b7cccd510a6'
      domain: 'kitchentest'
